server:
  port: 8282
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: service-feign
  rabbitmq:
    host: 172.23.160.148
    port: 5672
    username: root
    password: 123456
    virtual-host: my_vhost
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
      force-response: true

eureka:
  instance:
    status-page-url-path: /swagger-ui.html
  client:
    service-url:
      defaultZone: http://@eureka-hostname@:@eureka-port@/eureka/,http://localhost2:2001/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            # 超时时间，超过这个时间将进行服务降级
            timeoutInMilliseconds: 15000
feign:
  hystrix:
    enabled: true


swagger:
  title: feign-api
  description: feign接口
  version: 1.0.0
  name: XueYou
  url: xueyou.com
  email: xueyoucd@gmail.com